version: '2.6'
services:
  mysql-db:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: transaction
    ports:
      - '3307:3306'
    volumes:
      - mysql-backup:/var/lib/mysql

  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: transaction-service:1.0
    depends_on:
      - mysql-db
    ports:
      - '9091:8181'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/transaction?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
volumes:
  mysql-backup:

